### ISSUE TITLE
502 Bad Gateway // Screenshot For Readme

### ISSUE THREAD

**Issue by VernonSmith** [d4rky-pl/ffyf#1]
Hi,
I get the error `502 Bad Gateway` when visiting [http://fuckyeahfastfood.com/](http://fuckyeahfastfood.com/). Can you please check that?
What do you think of adding a screenshot to your Readme additionally?
Thanks!

**Comment by d4rky-pl** [comment]
@VernonSmith hey, this is a very old project that we built for Rails Rumbler in ~2014~ 2013 (woah, I didn't realize it's been so long!). I put it here for archival purposes and I do not plan on maintaining it anymore - I'm not even sure if the APIs are still the same, not to mention the application had critical performance bugs we never managed to squash.

Thanks for the interest though, if you want to fork this and continue developing the idea as your own, go ahead :)

**Comment by katafrakt** [comment]
> if you want to fork this and continue developing the idea as your own, go ahead :)

I'm afraid it won't be possible due to restrictions introduced to Instagram API, though.
